### ISSUE TITLE
Tests report 'invalid transaction termination' when failed

### ISSUE THREAD

**Issue by lbuchli** [geometalab/pgunit#1]
If any unit test fails, e.g.
```sql
create or replace function test_case_demo () returns void as $$
begin
    perform assertTrue(false);
end;
$$ language plpgsql;
```
 'invalid transaction termination' is returned instead of a fail flag and an error message.

**Comment by smilesT** [comment]
Added Exception Block in autonomous(p_statement VARCHAR) to forward the triggered_action_exception correctly to the calling function run_suite(p_suite TEXT).

If pgunit.assertTrue(false) is called, the Test fails with Error Message 'Condition Failure', which triggers the 'failed' field and not not the erroneous.
